name: Deploy website to S3
on:
  push:
    branches:
      - master

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'IBM-Design/design-website'
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@v1.4.0
        with:
          github_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: '10.15'

      - name: Install dependencies from offline mirror
        run: yarn install --offline

      - name: Build site
        run: yarn build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.COS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COS_ENDPOINT }}
          SOURCE_DIR: 'public/design'
          DEST_DIR: 'design'
