name: Deploy website to IBM Cloud
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@v1.4.0
        with:
          github_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 10.x

      - name: Install dependencies from offline mirror
        run: yarn install --offline

      - name: Build site
        run: yarn build

      - name: Install IBM Cloud CLI
        run: curl -fsSL https://clis.cloud.ibm.com/install/osx | sh

      - name: Install Cloud Foundry CLI
        run: ibmcloud cf install -v 6.51.0

      - name: Login to to US
        env:
          API_KEY: ${{ secrets.IBM_CLOUD_KEY_SLASH_DESIGN }}
        run: ibmcloud login -a https://api.ng.bluemix.net --apikey $API_KEY -o IBMDesignOrg -s slashDesign
      - name: Deploy to US
        run: ibmcloud cf v3-zdt-push slash-design-root -b https://github.com/cloudfoundry/nginx-buildpack.git
        
      - name: Login to to EU
        env:
          API_KEY: ${{ secrets.IBM_CLOUD_KEY_SLASH_DESIGN }}
        run: ibmcloud login -a https://api.eu-de.bluemix.net --apikey $API_KEY -o IBMDesignOrg -s slashDesign
      - name: Deploy to EU
        run: ibmcloud cf v3-zdt-push slash-design-root -b https://github.com/cloudfoundry/nginx-buildpack.git
